language: node_js

node_js:
 - "10"

services:
  - postgresql

addons:
  postgresql: "9.6"

before_script:
  - psql -c 'create database "area-api-db";' -U postgres

cache:
 directories:
   - node_modules

script:
  - npm install
  - npm run test

deploy:
  provider: heroku
  app: area-api-dev
  on:
    condition: $TRAVIS_BRANCH == develop
    repo: chikeozulumba/Area-API
    branch: develop
  api_key:
    secure: $HEROKU_AUTH