language: node_js

node_js:
 - "10"

services:
  - postgresql
  - redis-server

addons:
  postgresql: "9.6"

before_script:
  - psql -c 'create database "area-api-db";' -U postgres

cache:
 directories:
   - node_modules

script:
  - yarn install
  - yarn test

deploy:
  provider: heroku
  app: area-api-dev
  on:
    condition: $TRAVIS_BRANCH == develop
    repo: chikeozulumba/Area-API
    branch: develop
  api_key:
    secure: $HEROKU_AUTH

deploy:
  provider: heroku
  app: area-api-prod
  on:
    condition: $TRAVIS_BRANCH == master
    repo: chikeozulumba/Area-API
    branch: master
  api_key:
    secure: $HEROKU_AUTH